<?php
/**
 * @file
 * doc2.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function doc2_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-priv_documentation-field_doc_date'
  $field_instances['node-priv_documentation-field_doc_date'] = array(
    'bundle' => 'priv_documentation',
    'deleted' => 0,
    'description' => 'The date the file or document was last updated',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'date',
        'settings' => array(
          'format_type' => 'short',
          'fromto' => 'both',
          'multiple_from' => '',
          'multiple_number' => '',
          'multiple_to' => '',
        ),
        'type' => 'date_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_doc_date',
    'label' => 'Last Updated',
    'required' => 0,
    'settings' => array(
      'default_value' => 'now',
      'default_value2' => 'same',
      'default_value_code' => '',
      'default_value_code2' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'date',
      'settings' => array(
        'display_all_day' => 0,
        'increment' => 15,
        'input_format' => 'm/d/Y - H:i:s',
        'input_format_custom' => '',
        'label_position' => 'above',
        'text_parts' => array(),
        'year_range' => '-3:+3',
      ),
      'type' => 'date_popup',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'node-priv_documentation-field_doc_description'
  $field_instances['node-priv_documentation-field_doc_description'] = array(
    'bundle' => 'priv_documentation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Information about the Documentation.  Can use text from beginning of the document',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_doc_description',
    'label' => 'Description',
    'required' => 0,
    'settings' => array(
      'better_formats' => array(
        'allowed_formats' => array(
          'test_format' => 'test_format',
          1 => 1,
          2 => 2,
          3 => 3,
          4 => 4,
        ),
        'allowed_formats_toggle' => 0,
        'default_order_toggle' => 0,
        'default_order_wrapper' => array(
          'formats' => array(
            'test_format' => array(
              'weight' => -7,
            ),
            1 => array(
              'weight' => -9,
            ),
            2 => array(
              'weight' => -10,
            ),
            3 => array(
              'weight' => -8,
            ),
            4 => array(
              'weight' => -6,
            ),
          ),
        ),
      ),
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'node-priv_documentation-field_doc_myecw'
  $field_instances['node-priv_documentation-field_doc_myecw'] = array(
    'bundle' => 'priv_documentation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'The folder that the document is in on my.eclinicalworks.com (myecw)',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_doc_myecw',
    'label' => 'Myecw folder',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-priv_documentation-field_doc_priv_file'
  $field_instances['node-priv_documentation-field_doc_priv_file'] = array(
    'bundle' => 'priv_documentation',
    'deleted' => 0,
    'description' => 'These files are private',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'file',
        'settings' => array(),
        'type' => 'file_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_doc_priv_file',
    'label' => 'File',
    'required' => 0,
    'settings' => array(
      'description_field' => 0,
      'file_directory' => 'documentation',
      'file_extensions' => 'txt pdf doc docx xls xlsx zip',
      'max_filesize' => '100 MB',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'file',
      'settings' => array(
        'progress_indicator' => 'throbber',
      ),
      'type' => 'file_generic',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-priv_documentation-field_ebo_category'
  $field_instances['node-priv_documentation-field_ebo_category'] = array(
    'bundle' => 'priv_documentation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Sub-folders for eBO for use on Documentation and Videos',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_ebo_category',
    'label' => 'eBO Category',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'node-priv_documentation-field_internal_only'
  $field_instances['node-priv_documentation-field_internal_only'] = array(
    'bundle' => 'priv_documentation',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '<strong>Is this document internal only?</strong>',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_internal_only',
    'label' => 'Internal Only',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-priv_documentation-taxonomy_vocabulary_10'
  $field_instances['node-priv_documentation-taxonomy_vocabulary_10'] = array(
    'bundle' => 'priv_documentation',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'taxonomy_vocabulary_10',
    'label' => 'eCW Version',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 5,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('<strong>Is this document internal only?</strong>');
  t('Description');
  t('File');
  t('Information about the Documentation.  Can use text from beginning of the document');
  t('Internal Only');
  t('Last Updated');
  t('Myecw folder');
  t('Sub-folders for eBO for use on Documentation and Videos');
  t('The date the file or document was last updated');
  t('The folder that the document is in on my.eclinicalworks.com (myecw)');
  t('These files are private');
  t('eBO Category');
  t('eCW Version');

  return $field_instances;
}
